### PR TITLE
Fixes a case where end of range specified was greater than the size of array

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by blackwinter** [comment]
Thank you for this pull request. However, I would like you to address the following items before I can merge it:

* Add a failing test case and ensure that all tests pass after your fix.
* Move the conditional above `gsl_permutation_alloc` (first use of `n`).
* Change `>=` to `>` (there's no need for the assignment if both are equal).

**Comment by v0dro** [comment]
I added this test case because [this test](https://github.com/blackwinter/rb-gsl/blob/master/test/gsl/index_test.rb#L35) would fail on ruby 1.9.3 (I'll remove that guard now).

And yes I'll make the changes you requested.

**Comment by v0dro** [comment]
ok done

**Comment by blackwinter** [comment]
Thank you very much.

**Comment by v0dro** [comment]
any time :)

**Pull request merged**
