### PR TITLE
Add Rubinius to the CI build matrix

### PR DESCRIPTION
**Pull request by jc00ke**
Would help us in addressing #28.

### CODE REVIEW

**Comment by minad** [comment]
not good if you immediately delete the branch - travis cannot run through :-1:

**Comment by jc00ke** [comment]
My fork/branch never ran, and the merge of this one is [still running](https://travis-ci.org/blackwinter/rb-gsl/builds/67859837).

**Comment by minad** [comment]
This is not true - https://travis-ci.org/blackwinter/rb-gsl/builds/67858591

**Comment by jc00ke** [comment]
Hmm, my bad. I don't remember ever running in to that before. Branch restored, I can't restart the build.

**Comment by minad** [comment]
doesn't matter, I just wanted to look quickly. but now the other build ran through

**Comment by edmundhighcock** [comment]
Hi guys, thanks for working on this! I've now got rb-gsl to compile with rbx 2.5.2; only a tiny patch was required, but `rake test` is triggering a very rubinius-specific sort of error that I'm unfamiliar with.. I posted details here:

https://github.com/blackwinter/rb-gsl/issues/28#issuecomment-114168943

**Pull request merged**
